use etl1;
select*from national_stock_exchange_of_india_ltd;
/*                                               Nifty TOP 50 Stock Analysis                                                          */
--                     NIFTY-50 Stocks: Comprehensive Dataset from India's Top Companies on the NSE

-- renameing the datasets 
alter table national_stock_exchange_of_india_ltd rename to `NSE 50 stock`;
select*from `NSE 50 stock`;

-- Descriptive Analysis:
-- What is the average opening price (Open) for the Nifty TOP 50 stocks?
select round(avg(open)) from `nse 50 stock`; 
  
-- What is the highest and lowest closing price (LTP) observed in the dataset?
select max(LTP) as `highest closeing price` from `nse 50 stock`;
select min(ltp) as `lowest closeing price` from `nse 50 stock`;

-- How volatile are the stock prices? Calculate the standard deviation of the High and Low prices.
select std(high) as `highest volatile of niffty`  from `nse 50 stock`;
select std(low) as `lowest volatile of niffty` from `nse 50 stock`;

-- Overall Market Analysis

-- Identifying the top 5 Nifty 50 stocks with the highest percentage change (% Chng) for the day.
desc `NSE 50 stock`; -- overviewing data
select Symbol,LTP,`% Chng` from `nse 50 stock` order by `% Chng` desc limit 0,5;

-- Find the trading volume (Volume (lacs)) which are greater than avg trading daill volumn for all Nifty 50 stocks.
select Symbol,LTP,`Volume (lacs)` from `nse 50 stock` where `Volume (lacs)` > (select avg(`Volume (lacs)`) from `nse 50 stock`);

-- What is the average daily trading volume for all Nifty 50 stocks in the table?
select round(avg(`Volume (lacs)`)) from `nse 50 stock`;

-- What is the total turnover generated by all Nifty 50 stocks?
select round(sum(`Turnover (crs.)`)) from `nse 50 stock`;

-- Identify the stock with the highest and lowest average  trading volume. 

-- Stock with Highest Average Trading Volume:
select Symbol,avg(`volume (lacs)`) as avg_trading_volumn from `nse 50 stock` 
group by symbol order by avg_trading_volumn desc limit 1;

-- Stock with Lowest Average Trading Volume:
select Symbol,avg(`volume (lacs)`) as avg_trading_volumn from `nse 50 stock` 
group by symbol order by avg_trading_volumn limit 1;

-- Calculate the average and standard deviation of the percentage change (% Chng) for Nifty 50 stocks.
-- calcuating the avg percentage of change for nify 50 stock
select round(avg(`% chng`)) from `nse 50 stock`;

-- calcuating the standard devition percentage of change for nify 50 stock
select round(std(`% chng`)) from `nse 50 stock`;

-- Find the number of stocks currently trading above their 52-week high.
select count(distinct(`52w H`)) from `nse 50 stock`;

-- Stock Performance Analysis
-- For a specific stock, what is the difference between the opening and closing price (LTP)?
select symbol,open,ltp,open - ltp as `differnece` from `nse 50 stock`;

-- Identify the Nifty 50 stock with the highest and lowest percentage change (% Chng).

-- Stock with Highest percentage of chnage:
select symbol,`% chng` as `percentage of change` from `nse 50 stock` 
order by `percentage of change` desc limit 1;

-- Stock with lowest percentage of chnage:
select symbol,`% chng` as `percentage of change` from `nse 50 stock` 
order by `percentage of change` limit 1;

-- Analyze the correlation between a stock's current price (LTP) and its 52-week high or low.
select (avg(`LTP` * `52w h` or `52w l`) - avg(`LTP`) * avg(`52w h`) or avg(`52w l`)) / (std(`LTP`) * std(`52w h`) or avg(`52w l`)) as 
`correlation of current price and 52 week high or low` from `nse 50 stock`;

-- Compare the 365-day and 30-day percentage change for each stock and identify those with the most significant difference.
select symbol,`365 d % chng`,`30 d % chng`,`365 d % chng` - `30 d % chng` as `most significant diifernce` from `nse 50 stock`
order by `most significant diifernce` desc;
